[project]
name = 'Local-Experience-Curation-Engine'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.community-business-network]
path = 'contracts/community-business-network.clar'
clarity_version = 3
epoch = 'latest'

[contracts.cultural-experience-matcher]
path = 'contracts/cultural-experience-matcher.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
